### ISSUE TITLE
event.direct is true even when hearing a message from a channel

### ISSUE THREAD

**Issue by ivanmayes** [botpress/botpress-slack#12]
In testing, I'm unable to get the bot to send an event through with direct:false.  I'm assuming it's there to let someone know if the message is being direct messaged with the bot, but it doesn't seem to be working since it is true when just typing any text like 'hello' in a channel that the bot has joined.

**Comment by slvnperron** [comment]
Thanks Ivan. @DanyFS can you check this out?

**Comment by DanyFS** [comment]
@ivanmayes I just tried on my side and it seems to work. When a I send a message directly to the bot (`direct: true`) and in a channel (`direct: false`).

Probably, the issue was related to other issue you reported (#11). I think that the new channels you have created in your team where not updated by your bot. 

Here's the code that verify if a message is direct or not:

```
 const isDirect = (channelId) => {
    return !_.some(slack.getChannels(), { id: channelId })
  }
```

Let me know if everything is now working...

Thanks @ivanmayes!

**Comment by ivanmayes** [comment]
Ah, that would make sense, thanks for looking into that!
